INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Fruits', 'fruits', true, CURRENT_DATE, CURRENT_DATE, false, 'fruits', 'fruits', 'fruits');
INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Vegetables', 'vegetables', true, CURRENT_DATE, CURRENT_DATE, false, 'vegetables', 'vegetables', 'vegetables');
INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Dairy', 'dairy', true, CURRENT_DATE, CURRENT_DATE, false, 'dairy', 'dairy', 'dairy');
INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Meat', 'meat', true, CURRENT_DATE, CURRENT_DATE, false, 'meat', 'meat', 'meat');
INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Seafood', 'seafood', true, CURRENT_DATE, CURRENT_DATE, false, 'seafood', 'seafood', 'seafood');
INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Spices', 'spices', true, CURRENT_DATE, CURRENT_DATE, false, 'spices', 'spices', 'spices');
INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Baking', 'baking', true, CURRENT_DATE, CURRENT_DATE, false, 'baking', 'baking', 'baking');

INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (1, 'no5s5eje.lnt.jpg', 'ProductImage', null); -- apple
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (2, 'rpjgo4mx.ot2.jpg', 'ProductImage', null); -- apple (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (3, 'mn0ivtyj.kxb.jpg', 'ProductImage', null); -- banana
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (4, 'w3ljwbsk.gdm.jpg', 'ProductImage', null); -- banana (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (5, 'pwdvcick.ncj.jpg', 'ProductImage', null); -- beef
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (6, 'qxt334v4.bnp.jpg', 'ProductImage', null); -- beef (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (7, 'aiep4doc.oi4.jpg', 'ProductImage', null); -- butter
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (8, 'b5vvh2xo.0sj.jpg', 'ProductImage', null); -- butter (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (9, 'd4qjejsp.5eg.jpg', 'ProductImage', null); -- cabbage
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (10, 'vxj5je5n.xxh.jpg', 'ProductImage', null); -- cabbage (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (11, 's22j0hgl.vub.jpg', 'ProductImage', null); -- carrot
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (12, 'h5lcijdy.52c.jpg', 'ProductImage', null); -- carrot (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (13, 'se4t5a2h.gwa.jpg', 'ProductImage', null); -- cheese
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (14, 'j4wvilji.abx.jpg', 'ProductImage', null); -- cheese (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (15, '4vs2argg.zwh.jpg', 'ProductImage', null); -- chicken
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (16, 'z3sjx4qu.llt.jpg', 'ProductImage', null); -- chicken (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (17, '3jmtkglq.3cx.jpg', 'ProductImage', null); -- cinnamon
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (18, 'cwy0oqbf.iqa.jpg', 'ProductImage', null); -- cinnamon (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (19, 'pyea1d5x.1s4.jpg', 'ProductImage', null); -- flour
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (20, 'ookrdrum.rn4.jpg', 'ProductImage', null); -- flour (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (21, 'epgltvyy.rik.jpg', 'ProductImage', null); -- milk
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (22, 'ykdkuhhk.wgh.jpg', 'ProductImage', null); -- milk (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (23, 'prtyvymn.cfb.jpg', 'ProductImage', null); -- pepper
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (24, 'qyxl0gqo.3nl.jpg', 'ProductImage', null); -- pepper (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (25, 'thxeaenq.shc.jpg', 'ProductImage', null); -- pork
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (26, 't5zjz31b.sca.jpg', 'ProductImage', null); -- pork (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (27, 'c2a055ci.cqb.jpg', 'ProductImage', null); -- potato
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (28, 'fnktldsy.xmg.jpg', 'ProductImage', null); -- potato (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (29, 'rretuy4o.ten.jpg', 'ProductImage', null); -- salmon
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (30, 'h15wwrel.2fx.jpg', 'ProductImage', null); -- salmon (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (31, 'k5rkfvda.hv3.jpg', 'ProductImage', null); -- salt
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (32, 'gqu3o4ei.ob0.jpg', 'ProductImage', null); -- salt (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (33, 'sdto00b0.fae.jpg', 'ProductImage', null); -- shrimp
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (34, 'rqnsiz3n.2de.jpg', 'ProductImage', null); -- shrimp (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (35, 'tv30vyar.zbo.jpg', 'ProductImage', null); -- strawberry
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (36, 'todrwzdz.gok.jpg', 'ProductImage', null); -- strawberry (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (37, 'uiakkhla.frp.jpg', 'ProductImage', null); -- sugar
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (38, 'msys41yq.m4w.jpg', 'ProductImage', null); -- sugar (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (39, 'noinldze.ud1.jpg', 'ProductImage', null); -- tuna
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (40, 'cwillbek.co3.jpg', 'ProductImage', null); -- tuna (thumbnail)
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (41, '1kdo0uuj.abw.jpg', 'ProductImage', null); -- yeast
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (42, 'dtyoqmb3.fqt.jpg', 'ProductImage', null); -- yeast (thumbnail)
SELECT setval('images_id_seq', COALESCE(MAX(id), 1), true) FROM public.images;

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Strawberry', 'strawberry', 'strawberry', true, true, false, 3.99, 0.00, '<p>Juicy, sweet strawberries picked at peak ripeness for maximum flavor and freshness. Perfect for snacking, blending into smoothies, topping desserts, or adding to salads. Rich in vitamin C, antioxidants, and natural sweetness.</p>', 'Fresh, sweet strawberries perfect for snacking or recipes.', 1, (SELECT id from public.categories WHERE name = 'Fruits'), CURRENT_DATE, CURRENT_DATE, false, 'strawberry', 'strawberry', 'Buy fresh strawberries packed with sweetness and nutrients. Great for snacking, smoothies, desserts, and more.', 35, 36);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Apple', 'apple', 'apple', true, true, false, 1.99, 0.00, '<p>Crisp, juicy apples with a naturally sweet and refreshing flavor. Perfect for snacking, baking, juicing, or adding to salads. Apples are rich in fiber, vitamin C, and antioxidants, making them a delicious and nutritious everyday fruit.</p>', 'A fresh, nutritious apple, perfect for snacking, baking, and adding to recipes. Available in various varieties to suit every taste.', 1, (SELECT id from public.categories WHERE name = 'Fruits'), CURRENT_DATE, CURRENT_DATE, false, 'apple', 'apple', 'Discover the fresh, crisp taste of apples, packed with vitamins, fiber, and antioxidants. Perfect for snacking, baking, and adding to recipes.', 1, 2);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Banana', 'banana', 'banana', true, true, false, 0.25, 0.00, '<p>A ripe banana is a naturally sweet, soft-textured fruit with a bright yellow peel and creamy interior. Popular as a quick snack or ingredient in smoothies, cereals, and baked goods, bananas are a rich source of potassium, vitamin C, and dietary fiber.</p>', 'Fresh, ripe bananas packed with natural sweetness and nutrition.', 0.3, (SELECT id from public.categories WHERE name = 'Fruits'), CURRENT_DATE, CURRENT_DATE, false, 'banana', 'banana', 'Buy fresh bananas online. Naturally sweet and rich in potassium, perfect for snacking or adding to your favorite recipes.', 3, 4);

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Potato', 'potato', 'potato', true, true, false, 2.49, 0.00, '<p>Fresh, firm potatoes with smooth skin and starchy texture. Perfect for boiling, baking, mashing, or frying, they’re a versatile staple in countless dishes. A good source of potassium, vitamin C, and dietary fiber.</p>', 'Versatile, fresh potatoes great for baking, mashing, or frying.', 3, (SELECT id from public.categories WHERE name = 'Vegetables'), CURRENT_DATE, CURRENT_DATE, false, 'potato', 'potato', 'Buy fresh potatoes ideal for roasting, mashing, or frying. A nutritious and versatile staple for everyday cooking.', 27, 28);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Carrot', 'carrot', 'carrot', true, true, false, 1.29, 0.00, '<p>Crunchy, sweet carrots harvested fresh for maximum flavor and nutrition. Excellent for snacking, cooking, or juicing, they’re a rich source of beta-carotene, fiber, and essential vitamins. Ideal for salads, soups, and roasted dishes.</p>', 'Fresh, sweet carrots perfect for snacking, cooking, or juicing.', 1, (SELECT id from public.categories WHERE name = 'Vegetables'), CURRENT_DATE, CURRENT_DATE, false, 'carrot', 'carrot', 'Shop fresh carrots full of flavor and nutrients. Great for salads, soups, roasting, or snacking straight from the bag.', 11, 12);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Cabbage', 'cabbage', 'cabbage', true, true, false, 1.99, 0.00, '<p>Fresh green cabbage with crisp, tightly packed leaves. Mild in flavor and versatile in the kitchen, it’s perfect for salads, stir-fries, soups, and fermentation. A great source of vitamins C and K, as well as dietary fiber.</p>', 'Crisp, fresh cabbage great for salads, cooking, or pickling.', 2, (SELECT id from public.categories WHERE name = 'Vegetables'), CURRENT_DATE, CURRENT_DATE, false, 'cabbage', 'cabbage', 'Buy fresh green cabbage, perfect for slaws, stir-fries, and soups. Packed with nutrients and natural crunch.', 9, 10);

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Milk', 'milk', 'milk', true, true, false, 3.29, 0.00, '<p>Fresh, wholesome milk sourced from quality dairy farms. Smooth and naturally rich in calcium, it&#39;s perfect for drinking, cooking, or adding to coffee, cereal, and smoothies. A daily essential for nutrition and taste.</p>', 'Fresh, creamy milk ideal for drinking, cooking, or baking.', 8.6, (SELECT id from public.categories WHERE name = 'Dairy'), CURRENT_DATE, CURRENT_DATE, false, 'milk', 'milk', 'Buy fresh milk packed with calcium and essential nutrients. Great for drinking, cereal, coffee, and everyday recipes.', 21, 22);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Cheese', 'cheese', 'cheese', true, true, false, 5.49, 0.00, '<p>Rich, flavorful cheese crafted from quality dairy. Smooth and creamy with a balanced taste, it’s perfect for sandwiches, cooking, snacking, or melting over your favorite dishes. A good source of calcium and protein.</p>', 'Creamy, flavorful cheese great for melting, snacking, or cooking.', 1, (SELECT id from public.categories WHERE name = 'Dairy'), CURRENT_DATE, CURRENT_DATE, false, 'cheese', 'cheese', 'Buy fresh, high-quality cheese with rich flavor and creamy texture. Perfect for cooking, snacking, or adding to your favorite meals.', 13, 14);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Butter', 'butter', 'butter', true, true, false, 4.49, 0.00, '<p>Creamy, rich butter made from high-quality dairy. Perfect for baking, cooking, or spreading, it adds smooth texture and deep flavor to a wide range of dishes. Made with simple ingredients and no artificial additives.</p>', 'Rich, creamy butter ideal for baking, cooking, or spreading.', 1, (SELECT id from public.categories WHERE name = 'Dairy'), CURRENT_DATE, CURRENT_DATE, false, 'butter', 'butter', 'Shop fresh, creamy butter made from quality dairy. Ideal for cooking, baking, or spreading on your favorite foods.', 7, 8);

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Chicken', 'chicken', 'chicken', true, true, false, 4.99, 0.00, '<p>Fresh, tender chicken sourced from quality farms and prepared for a variety of cooking methods. Whether grilled, baked, roasted, or fried, chicken is a lean and versatile protein option suitable for everyday meals.</p>', 'Fresh, tender chicken perfect for grilling, baking, or frying.', 1, (SELECT id from public.categories WHERE name = 'Meat'), CURRENT_DATE, CURRENT_DATE, false, 'chicken', 'chicken', 'Shop fresh chicken, a lean and versatile protein for any meal. Ideal for grilling, roasting, or your favorite homemade recipes.', 15, 16);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Beef', 'beef', 'beef', true, true, false, 7.99, 0.00, '<p>Premium quality beef, hand-trimmed and rich in flavor. Ideal for grilling, roasting, or slow-cooking, this versatile protein is a staple in countless savory dishes. Sourced from responsibly raised cattle to ensure freshness and tenderness.</p>', 'High-quality beef perfect for grilling, roasting, or stews.', 1, (SELECT id from public.categories WHERE name = 'Meat'), CURRENT_DATE, CURRENT_DATE, false, 'beef', 'beef', 'Shop fresh, premium beef perfect for any meal. Tender, flavorful, and ideal for grilling, roasting, or slow-cooked recipes.', 5, 6);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Pork', 'pork', 'pork', true, true, false, 5.99, 0.00, '<p>Fresh, tender pork sourced from quality farms and carefully prepared for a variety of cooking styles. Ideal for grilling, roasting, frying, or slow-cooking, pork offers rich flavor and versatility for everyday meals or special occasions.</p>', 'Fresh, flavorful pork perfect for grilling, roasting, or frying.', 1, (SELECT id from public.categories WHERE name = 'Meat'), CURRENT_DATE, CURRENT_DATE, false, 'pork', 'pork', 'Shop fresh pork with rich flavor and tender texture. Great for grilling, roasting, or your favorite home-cooked recipes.', 25, 26);

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Salmon', 'salmon', 'salmon', true, true, false, 9.99, 0.00, '<p>Fresh, premium salmon with a rich, buttery texture and vibrant color. Perfect for grilling, baking, or pan-searing, this high-quality fish is an excellent source of protein and omega-3 fatty acids. Ideal for both everyday meals and special occasions.</p>', 'Fresh, flavorful salmon rich in protein and omega-3s.', 1, (SELECT id from public.categories WHERE name = 'Seafood'), CURRENT_DATE, CURRENT_DATE, false, 'salmon', 'salmon', 'Shop fresh salmon with rich flavor and high nutritional value. Great for grilling, baking, or pan-searing in a variety of dishes.', 29, 30);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Tuna', 'tuna', 'tuna', true, true, false, 7.49, 0.00, '<p>Fresh, high-quality tuna with a firm texture and mild, clean flavor. Perfect for grilling, searing, or adding to salads and bowls. Packed with protein and omega-3 fatty acids, tuna is a nutritious and flavorful seafood choice.</p>', 'Fresh, lean tuna great for grilling, searing, or salads.', 1, (SELECT id from public.categories WHERE name = 'Seafood'), CURRENT_DATE, CURRENT_DATE, false, 'tuna', 'tuna', 'Buy fresh tuna rich in protein and omega-3s. Ideal for grilling, salads, and light, healthy meals.', 39, 40);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Shrimp', 'shrimp', 'shrimp', true, true, false, 8.99, 0.00, '<p>Fresh, succulent shrimp with a tender texture and mild, sweet flavor. Perfect for grilling, sautéing, boiling, or adding to pastas, salads, and stir-fries. A lean source of protein that&#39;s quick to cook and easy to enjoy.</p>', 'Tender, flavorful shrimp great for grilling, sautéing, or boiling.', 1, (SELECT id from public.categories WHERE name = 'Seafood'), CURRENT_DATE, CURRENT_DATE, false, 'shrimp', 'shrimp', 'Shop fresh shrimp with sweet flavor and tender bite. Ideal for grilling, pastas, stir-fries, and quick meals.', 33, 34);

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Salt', 'salt', 'salt', true, true, false, 0.99, 0.00, '<p>Pure, fine-grain salt perfect for everyday cooking and seasoning. Enhances the natural flavors of any dish, from meats and vegetables to soups and sauces. A kitchen essential with clean taste and reliable performance.</p>', 'Fine-grain salt ideal for cooking, seasoning, and baking.', 1, (SELECT id from public.categories WHERE name = 'Spices'), CURRENT_DATE, CURRENT_DATE, false, 'salt', 'salt', 'Buy pure cooking salt to enhance flavor in any recipe. A kitchen staple for seasoning, baking, and everyday meals.', 31, 32);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Pepper', 'pepper', 'pepper', true, true, false, 2.99, 0.00, '<p>Bold and aromatic black pepper, freshly ground for maximum flavor. A kitchen staple that enhances the taste of virtually any savory dish, from meats and vegetables to soups and sauces. Naturally rich in antioxidants and spice.</p>', 'Fresh ground black pepper for bold, aromatic seasoning.', 0.25, (SELECT id from public.categories WHERE name = 'Spices'), CURRENT_DATE, CURRENT_DATE, false, 'pepper', 'pepper', 'Shop fresh black pepper for bold flavor and aroma. Perfect for seasoning meats, vegetables, soups, and everyday dishes.', 23, 24);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Cinnamon', 'cinnamon', 'cinnamon', true, true, false, 2.49, 0.00, '<p>Aromatic and warm, this ground cinnamon adds depth and sweetness to both sweet and savory dishes. Sourced from premium cinnamon bark, it&#39;s perfect for baking, beverages, oatmeal, and spice blends. Naturally rich in flavor and aroma.</p>', 'Warm, aromatic ground cinnamon perfect for baking and cooking.', 0.25, (SELECT id from public.categories WHERE name = 'Spices'), CURRENT_DATE, CURRENT_DATE, false, 'cinnamon', 'cinnamon', 'Buy premium ground cinnamon for rich, warm flavor in baking, beverages, and more. A kitchen staple for sweet and savory recipes.', 17, 18);

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Flour', 'flour', 'flour', true, true, false, 3.99, 0.00, '<p>High-quality all-purpose flour milled for consistent texture and performance. Ideal for baking bread, pastries, cookies, and more. A pantry essential for both everyday cooking and special recipes, with excellent absorbency and versatility.</p>', 'Versatile all-purpose flour perfect for baking and cooking.', 5, (SELECT id from public.categories WHERE name = 'Baking'), CURRENT_DATE, CURRENT_DATE, false, 'flour', 'flour', 'Shop all-purpose flour for all your baking needs. Perfect for bread, cookies, cakes, and more. A kitchen staple with reliable performance.', 19, 20);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Sugar', 'sugar', 'sugar', true, true, false, 2.79, 0.00, '<p>Granulated white sugar with a fine, consistent texture ideal for baking, sweetening beverages, and everyday cooking. A pantry essential that adds just the right amount of sweetness to your favorite recipes.</p>', 'Fine granulated sugar perfect for baking and sweetening.', 4, (SELECT id from public.categories WHERE name = 'Baking'), CURRENT_DATE, CURRENT_DATE, false, 'sugar', 'sugar', 'Shop granulated sugar for baking, cooking, and sweetening drinks. A kitchen staple with consistent texture and reliable sweetness.', 37, 38);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, description, short_description, weight, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Yeast', 'yeast', 'yeast', true, true, false, 1.59, 0.00, '<p>Active dry yeast ideal for baking bread, rolls, and other homemade baked goods. Reliable and easy to use, it helps dough rise with consistent results. A must-have for any home baker looking to achieve fluffy, airy textures.</p>', 'Active dry yeast perfect for bread, rolls, and baking.', 0.25, (SELECT id from public.categories WHERE name = 'Baking'), CURRENT_DATE, CURRENT_DATE, false, 'yeast', 'yeast', 'Shop active dry yeast for reliable baking results. Great for making bread, rolls, and other homemade treats.', 41, 42);
