INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Fruits', 'fruits', true, CURRENT_DATE, CURRENT_DATE, false, 'fruits', 'fruits', 'fruits');
INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Vegetables', 'vegetables', true, CURRENT_DATE, CURRENT_DATE, false, 'vegetables', 'vegetables', 'vegetables');
INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Dairy', 'dairy', true, CURRENT_DATE, CURRENT_DATE, false, 'dairy', 'dairy', 'dairy');
INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Meat', 'meat', true, CURRENT_DATE, CURRENT_DATE, false, 'meat', 'meat', 'meat');
INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Seafood', 'seafood', true, CURRENT_DATE, CURRENT_DATE, false, 'seafood', 'seafood', 'seafood');
INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Spices', 'spices', true, CURRENT_DATE, CURRENT_DATE, false, 'spices', 'spices', 'spices');
INSERT INTO public.categories (name, url_key, is_enabled, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description) VALUES ('Baking', 'baking', true, CURRENT_DATE, CURRENT_DATE, false, 'baking', 'baking', 'baking');

INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (1, 'owyt5qv0.4ck.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (2, 'dqy2io14.fuj.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (3, 'pdtcpe23.lji.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (4, 'pdh12qn2.vx2.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (5, 'wo1soe5d.a12.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (6, 'p1nowucc.gtd.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (7, '4efsb4q0.wef.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (8, 'yjr1hpqk.gsr.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (9, 'mtpsl2o4.zaf.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (10, 'k45sxddm.wrs.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (11, 'sb3tcmex.5fg.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (12, 'duayac5z.bku.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (13, '3w2yqc2a.jgn.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (14, 'p4ibpkbb.z1t.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (15, 'udk30eqg.mpt.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (16, 'xd0ef5ey.p2u.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (17, 'r5v3jxpp.rpv.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (18, 'shjtyxez.fi5.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (19, 'rn0ezwcq.khr.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (20, 'cfegu1l2.uk1.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (21, 'dr1z20dh.qeu.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (22, 'npnmfn5l.2kt.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (23, 'v2vw43k0.2ga.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (24, 'bd3rlhta.2fw.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (25, 'apv5gyw1.qgr.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (26, 'q242lx1t.sqp.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (27, 'j04ph2ki.vd4.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (28, '2qboppp1.oc0.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (29, 'ci5jo4kn.zgg.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (30, 'g11idsmk.sad.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (31, 'n0zo2zmj.j2d.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (32, 'j2vpxtwb.knu.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (33, 'zkodizj0.pur.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (34, 'ucpzhi0x.rqk.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (35, 'kn5foj3d.qvv.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (36, '0zwngr3e.jli.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (37, 'j3iccpkx.gpq.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (38, 'zsqlzlhv.2lb.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (39, '11bk51s5.c0p.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (40, 'zu2a04pu.gdt.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (41, 'tz1nbk0b.pj3.png', 'ProductImage', null);
INSERT INTO public.images (id, file_name, discriminator, product_id) VALUES (42, 'ss3uozpb.jhx.png', 'ProductImage', null);
SELECT setval('images_id_seq', COALESCE(MAX(id), 1), true) FROM public.images;

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Strawberry', 'strawberry', 'strawberry', true, true, false, 10.00, 0.00, 'Strawberry', (SELECT id from public.categories WHERE name = 'Fruits'), CURRENT_DATE, CURRENT_DATE, false, 'strawberry', 'strawberry', 'strawberry', 35, 36);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Apple', 'apple', 'apple', true, true, false, 5.00, 0.00, 'Apple', (SELECT id from public.categories WHERE name = 'Fruits'), CURRENT_DATE, CURRENT_DATE, false, 'apple', 'apple', 'apple', 1, 2);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Banana', 'banana', 'banana', true, true, false, 3.00, 0.00, 'Banana', (SELECT id from public.categories WHERE name = 'Fruits'), CURRENT_DATE, CURRENT_DATE, false, 'banana', 'banana', 'banana', 3, 4);

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Potato', 'potato', 'potato', true, true, false, 3.00, 0.00, 'Potato', (SELECT id from public.categories WHERE name = 'Vegetables'), CURRENT_DATE, CURRENT_DATE, false, 'potato', 'potato', 'potato', 27, 28);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Carrot', 'carrot', 'carrot', true, true, false, 2.00, 0.00, 'Carrot', (SELECT id from public.categories WHERE name = 'Vegetables'), CURRENT_DATE, CURRENT_DATE, false, 'carrot', 'carrot', 'carrot', 11, 12);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Cabbage', 'cabbage', 'cabbage', true, true, false, 1.00, 0.00, 'Cabbage', (SELECT id from public.categories WHERE name = 'Vegetables'), CURRENT_DATE, CURRENT_DATE, false, 'cabbage', 'cabbage', 'cabbage', 9, 10);

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Milk', 'milk', 'milk', true, true, false, 1.00, 0.00, 'Milk', (SELECT id from public.categories WHERE name = 'Dairy'), CURRENT_DATE, CURRENT_DATE, false, 'milk', 'milk', 'milk', 21, 22);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Cheese', 'cheese', 'cheese', true, true, false, 2.00, 0.00, 'Cheese', (SELECT id from public.categories WHERE name = 'Dairy'), CURRENT_DATE, CURRENT_DATE, false, 'cheese', 'cheese', 'cheese', 13, 14);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Butter', 'butter', 'butter', true, true, false, 3.00, 0.00, 'Butter', (SELECT id from public.categories WHERE name = 'Dairy'), CURRENT_DATE, CURRENT_DATE, false, 'butter', 'butter', 'butter', 7, 8);

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Chicken', 'chicken', 'chicken', true, true, false, 5.00, 0.00, 'Chicken', (SELECT id from public.categories WHERE name = 'Meat'), CURRENT_DATE, CURRENT_DATE, false, 'chicken', 'chicken', 'chicken', 15, 16);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Beef', 'beef', 'beef', true, true, false, 10.00, 0.00, 'Beef', (SELECT id from public.categories WHERE name = 'Meat'), CURRENT_DATE, CURRENT_DATE, false, 'beef', 'beef', 'beef', 5, 6);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Pork', 'pork', 'pork', true, true, false, 8.00, 0.00, 'Pork', (SELECT id from public.categories WHERE name = 'Meat'), CURRENT_DATE, CURRENT_DATE, false, 'pork', 'pork', 'pork', 25, 26);

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Salmon', 'salmon', 'salmon', true, true, false, 15.00, 0.00, 'Salmon', (SELECT id from public.categories WHERE name = 'Seafood'), CURRENT_DATE, CURRENT_DATE, false, 'salmon', 'salmon', 'salmon', 29, 30);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Tuna', 'tuna', 'tuna', true, true, false, 12.00, 0.00, 'Tuna', (SELECT id from public.categories WHERE name = 'Seafood'), CURRENT_DATE, CURRENT_DATE, false, 'tuna', 'tuna', 'tuna', 39, 40);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Shrimp', 'shrimp', 'shrimp', true, true, false, 20.00, 0.00, 'Shrimp', (SELECT id from public.categories WHERE name = 'Seafood'), CURRENT_DATE, CURRENT_DATE, false, 'shrimp', 'shrimp', 'shrimp', 33, 34);

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Salt', 'salt', 'salt', true, true, false, 1.00, 0.00, 'Salt', (SELECT id from public.categories WHERE name = 'Spices'), CURRENT_DATE, CURRENT_DATE, false, 'salt', 'salt', 'salt', 31, 32);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Pepper', 'pepper', 'pepper', true, true, false, 2.00, 0.00, 'Pepper', (SELECT id from public.categories WHERE name = 'Spices'), CURRENT_DATE, CURRENT_DATE, false, 'pepper', 'pepper', 'pepper', 23, 24);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Cinnamon', 'cinnamon', 'cinnamon', true, true, false, 3.00, 0.00, 'Cinnamon', (SELECT id from public.categories WHERE name = 'Spices'), CURRENT_DATE, CURRENT_DATE, false, 'cinnamon', 'cinnamon', 'cinnamon', 17, 18);

INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Flour', 'flour', 'flour', true, true, false, 4.00, 0.00, 'Flour', (SELECT id from public.categories WHERE name = 'Baking'), CURRENT_DATE, CURRENT_DATE, false, 'flour', 'flour', 'flour', 19, 20);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Sugar', 'sugar', 'sugar', true, true, false, 3.00, 0.00, 'Sugar', (SELECT id from public.categories WHERE name = 'Baking'), CURRENT_DATE, CURRENT_DATE, false, 'sugar', 'sugar', 'sugar', 37, 38);
INSERT INTO public.products (name, url_key, sku, is_enabled, is_in_stock, is_discounted, base_price, discount_amount, short_description, category_id, date_created, date_modified, deleted, meta_title, meta_keywords, meta_description, main_image_id, thumbnail_image_id) VALUES ('Yeast', 'yeast', 'yeast', true, true, false, 2.00, 0.00, 'Yeast', (SELECT id from public.categories WHERE name = 'Baking'), CURRENT_DATE, CURRENT_DATE, false, 'yeast', 'yeast', 'yeast', 41, 42);
