using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace EndPointCommerce.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class CreateCountries : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "countries",
                columns: table => new
                {
                    id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    name = table.Column<string>(type: "text", nullable: false),
                    code = table.Column<string>(type: "text", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_countries", x => x.id);
                });

            migrationBuilder.InsertData(
                table: "countries",
                columns: new[] { "id", "code", "name" },
                values: new object[,]
                {
                    { 1, "AF", "Afghanistan" },
                    { 2, "AL", "Albania" },
                    { 3, "DZ", "Algeria" },
                    { 4, "AS", "American Samoa" },
                    { 5, "AD", "Andorra" },
                    { 6, "AO", "Angola" },
                    { 7, "AI", "Anguilla" },
                    { 8, "AQ", "Antarctica" },
                    { 9, "AG", "Antigua And Barbuda" },
                    { 10, "AR", "Argentina" },
                    { 11, "AM", "Armenia" },
                    { 12, "AW", "Aruba" },
                    { 13, "AU", "Australia" },
                    { 14, "AT", "Austria" },
                    { 15, "AZ", "Azerbaijan" },
                    { 16, "BS", "Bahamas" },
                    { 17, "BH", "Bahrain" },
                    { 18, "BD", "Bangladesh" },
                    { 19, "BB", "Barbados" },
                    { 20, "BY", "Belarus" },
                    { 21, "BE", "Belgium" },
                    { 22, "BZ", "Belize" },
                    { 23, "BJ", "Benin" },
                    { 24, "BM", "Bermuda" },
                    { 25, "BT", "Bhutan" },
                    { 26, "BO", "Bolivia" },
                    { 27, "BA", "Bosnia And Herzegowina" },
                    { 28, "BW", "Botswana" },
                    { 29, "BV", "Bouvet Island" },
                    { 30, "BR", "Brazil" },
                    { 31, "IO", "British Indian Ocean Territory" },
                    { 32, "BN", "Brunei Darussalam" },
                    { 33, "BG", "Bulgaria" },
                    { 34, "BF", "Burkina Faso" },
                    { 35, "BI", "Burundi" },
                    { 36, "KH", "Cambodia" },
                    { 37, "CM", "Cameroon" },
                    { 38, "CA", "Canada" },
                    { 39, "CV", "Cape Verde" },
                    { 40, "KY", "Cayman Islands" },
                    { 41, "CF", "Central African Republic" },
                    { 42, "TD", "Chad" },
                    { 43, "CL", "Chile" },
                    { 44, "CN", "China" },
                    { 45, "CX", "Christmas Island" },
                    { 46, "CC", "Cocos (Keeling) Islands" },
                    { 47, "CO", "Colombia" },
                    { 48, "KM", "Comoros" },
                    { 49, "CG", "Congo" },
                    { 50, "CD", "Congo, The Democratic Republic Of The" },
                    { 51, "CK", "Cook Islands" },
                    { 52, "CR", "Costa Rica" },
                    { 53, "CI", "Cote D'ivoire" },
                    { 54, "HR", "Croatia (Local Name: Hrvatska)" },
                    { 55, "CU", "Cuba" },
                    { 56, "CY", "Cyprus" },
                    { 57, "CZ", "Czech Republic" },
                    { 58, "DK", "Denmark" },
                    { 59, "DJ", "Djibouti" },
                    { 60, "DM", "Dominica" },
                    { 61, "DO", "Dominican Republic" },
                    { 62, "TP", "East Timor" },
                    { 63, "EC", "Ecuador" },
                    { 64, "EG", "Egypt" },
                    { 65, "SV", "El Salvador" },
                    { 66, "GQ", "Equatorial Guinea" },
                    { 67, "ER", "Eritrea" },
                    { 68, "EE", "Estonia" },
                    { 69, "ET", "Ethiopia" },
                    { 70, "FK", "Falkland Islands (Malvinas)" },
                    { 71, "FO", "Faroe Islands" },
                    { 72, "FJ", "Fiji" },
                    { 73, "FI", "Finland" },
                    { 74, "FR", "France" },
                    { 75, "FX", "France, Metropolitan" },
                    { 76, "GF", "French Guiana" },
                    { 77, "PF", "French Polynesia" },
                    { 78, "TF", "French Southern Territories" },
                    { 79, "GA", "Gabon" },
                    { 80, "GM", "Gambia" },
                    { 81, "GE", "Georgia" },
                    { 82, "DE", "Germany" },
                    { 83, "GH", "Ghana" },
                    { 84, "GI", "Gibraltar" },
                    { 85, "GR", "Greece" },
                    { 86, "GL", "Greenland" },
                    { 87, "GD", "Grenada" },
                    { 88, "GP", "Guadeloupe" },
                    { 89, "GU", "Guam" },
                    { 90, "GT", "Guatemala" },
                    { 91, "GN", "Guinea" },
                    { 92, "GW", "Guinea-bissau" },
                    { 93, "GY", "Guyana" },
                    { 94, "HT", "Haiti" },
                    { 95, "HM", "Heard And Mc Donald Islands" },
                    { 96, "VA", "Holy See (Vatican City State)" },
                    { 97, "HN", "Honduras" },
                    { 98, "HK", "Hong Kong" },
                    { 99, "HU", "Hungary" },
                    { 100, "IS", "Iceland" },
                    { 101, "IN", "India" },
                    { 102, "ID", "Indonesia" },
                    { 103, "IR", "Iran (Islamic Republic Of)" },
                    { 104, "IQ", "Iraq" },
                    { 105, "IE", "Ireland" },
                    { 106, "IL", "Israel" },
                    { 107, "IT", "Italy" },
                    { 108, "JM", "Jamaica" },
                    { 109, "JP", "Japan" },
                    { 110, "JO", "Jordan" },
                    { 111, "KZ", "Kazakhstan" },
                    { 112, "KE", "Kenya" },
                    { 113, "KI", "Kiribati" },
                    { 114, "KP", "Korea, Democratic People's Republic Of" },
                    { 115, "KR", "Korea, Republic Of" },
                    { 116, "KW", "Kuwait" },
                    { 117, "KG", "Kyrgyzstan" },
                    { 118, "LA", "Lao People's Democratic Republic" },
                    { 119, "LV", "Latvia" },
                    { 120, "LB", "Lebanon" },
                    { 121, "LS", "Lesotho" },
                    { 122, "LR", "Liberia" },
                    { 123, "LY", "Libyan Arab Jamahiriya" },
                    { 124, "LI", "Liechtenstein" },
                    { 125, "LT", "Lithuania" },
                    { 126, "LU", "Luxembourg" },
                    { 127, "MO", "Macau" },
                    { 128, "MK", "Macedonia, The Former Yugoslav Republic Of" },
                    { 129, "MG", "Madagascar" },
                    { 130, "MW", "Malawi" },
                    { 131, "MY", "Malaysia" },
                    { 132, "MV", "Maldives" },
                    { 133, "ML", "Mali" },
                    { 134, "MT", "Malta" },
                    { 135, "MH", "Marshall Islands" },
                    { 136, "MQ", "Martinique" },
                    { 137, "MR", "Mauritania" },
                    { 138, "MU", "Mauritius" },
                    { 139, "YT", "Mayotte" },
                    { 140, "MX", "Mexico" },
                    { 141, "FM", "Micronesia, Federated States Of" },
                    { 142, "MD", "Moldova, Republic Of" },
                    { 143, "MC", "Monaco" },
                    { 144, "MN", "Mongolia" },
                    { 145, "MS", "Montserrat" },
                    { 146, "MA", "Morocco" },
                    { 147, "MZ", "Mozambique" },
                    { 148, "MM", "Myanmar" },
                    { 149, "NA", "Namibia" },
                    { 150, "NR", "Nauru" },
                    { 151, "NP", "Nepal" },
                    { 152, "NL", "Netherlands" },
                    { 153, "AN", "Netherlands Antilles" },
                    { 154, "NC", "New Caledonia" },
                    { 155, "NZ", "New Zealand" },
                    { 156, "NI", "Nicaragua" },
                    { 157, "NE", "Niger" },
                    { 158, "NG", "Nigeria" },
                    { 159, "NU", "Niue" },
                    { 160, "NF", "Norfolk Island" },
                    { 161, "MP", "Northern Mariana Islands" },
                    { 162, "NO", "Norway" },
                    { 163, "OM", "Oman" },
                    { 164, "PK", "Pakistan" },
                    { 165, "PW", "Palau" },
                    { 166, "PA", "Panama" },
                    { 167, "PG", "Papua New Guinea" },
                    { 168, "PY", "Paraguay" },
                    { 169, "PE", "Peru" },
                    { 170, "PH", "Philippines" },
                    { 171, "PN", "Pitcairn" },
                    { 172, "PL", "Poland" },
                    { 173, "PT", "Portugal" },
                    { 174, "PR", "Puerto Rico" },
                    { 175, "QA", "Qatar" },
                    { 176, "RE", "Reunion" },
                    { 177, "RO", "Romania" },
                    { 178, "RU", "Russian Federation" },
                    { 179, "RW", "Rwanda" },
                    { 180, "KN", "Saint Kitts And Nevis" },
                    { 181, "LC", "Saint Lucia" },
                    { 182, "VC", "Saint Vincent And The Grenadines" },
                    { 183, "WS", "Samoa" },
                    { 184, "SM", "San Marino" },
                    { 185, "ST", "Sao Tome And Principe" },
                    { 186, "SA", "Saudi Arabia" },
                    { 187, "SN", "Senegal" },
                    { 188, "SC", "Seychelles" },
                    { 189, "SL", "Sierra Leone" },
                    { 190, "SG", "Singapore" },
                    { 191, "SK", "Slovakia (Slovak Republic)" },
                    { 192, "SI", "Slovenia" },
                    { 193, "SB", "Solomon Islands" },
                    { 194, "SO", "Somalia" },
                    { 195, "ZA", "South Africa" },
                    { 196, "GS", "South Georgia And The South Sandwich Islands" },
                    { 197, "ES", "Spain" },
                    { 198, "LK", "Sri Lanka" },
                    { 199, "SH", "St. Helena" },
                    { 200, "PM", "St. Pierre And Miquelon" },
                    { 201, "SD", "Sudan" },
                    { 202, "SR", "Suriname" },
                    { 203, "SJ", "Svalbard And Jan Mayen Islands" },
                    { 204, "SZ", "Swaziland" },
                    { 205, "SE", "Sweden" },
                    { 206, "CH", "Switzerland" },
                    { 207, "SY", "Syrian Arab Republic" },
                    { 208, "TW", "Taiwan, Province Of China" },
                    { 209, "TJ", "Tajikistan" },
                    { 210, "TZ", "Tanzania, United Republic Of" },
                    { 211, "TH", "Thailand" },
                    { 212, "TG", "Togo" },
                    { 213, "TK", "Tokelau" },
                    { 214, "TO", "Tonga" },
                    { 215, "TT", "Trinidad And Tobago" },
                    { 216, "TN", "Tunisia" },
                    { 217, "TR", "Turkey" },
                    { 218, "TM", "Turkmenistan" },
                    { 219, "TC", "Turks And Caicos Islands" },
                    { 220, "TV", "Tuvalu" },
                    { 221, "UG", "Uganda" },
                    { 222, "UA", "Ukraine" },
                    { 223, "AE", "United Arab Emirates" },
                    { 224, "GB", "United Kingdom" },
                    { 225, "US", "United States" },
                    { 226, "UM", "United States Minor Outlying Islands" },
                    { 227, "UY", "Uruguay" },
                    { 228, "UZ", "Uzbekistan" },
                    { 229, "VU", "Vanuatu" },
                    { 230, "VE", "Venezuela" },
                    { 231, "VN", "Viet Nam" },
                    { 232, "VG", "Virgin Islands (British)" },
                    { 233, "VI", "Virgin Islands (U.S.)" },
                    { 234, "WF", "Wallis And Futuna Islands" },
                    { 235, "EH", "Western Sahara" },
                    { 236, "YE", "Yemen" },
                    { 237, "YU", "Yugoslavia" },
                    { 238, "ZM", "Zambia" },
                    { 239, "ZW", "Zimbabwe" }
                });

            migrationBuilder.CreateIndex(
                name: "ix_countries_code",
                table: "countries",
                column: "code",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "countries");
        }
    }
}
