#!/bin/bash
# Copyright 2025 End Point Corporation. Apache License, version 2.0.

set -e

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
    CREATE USER $END_POINT_ECOMMERCE_DB_USERNAME;
    CREATE DATABASE $END_POINT_ECOMMERCE_DB;
    GRANT ALL PRIVILEGES ON DATABASE $END_POINT_ECOMMERCE_DB TO $END_POINT_ECOMMERCE_DB_USERNAME;
    ALTER DATABASE $END_POINT_ECOMMERCE_DB OWNER TO $END_POINT_ECOMMERCE_DB_USERNAME;
    ALTER USER $END_POINT_ECOMMERCE_DB_USERNAME WITH ENCRYPTED PASSWORD '$(cat $END_POINT_ECOMMERCE_DB_PASSWORD_FILE)';
EOSQL

# /usr/lib/postgresql/15/bin/pg_ctl restart
